### ISSUE TITLE
Add a medicine Page

### ISSUE THREAD

**Issue by Noelle-San** [Noelle-San/Help-in-Covid#12]
Add a new Page "Medicine.html "

In the page write proper medicines that helps if affected by the virus. Give pictures too.
Also style the UI.

**Comment by zainulabideen1122** [comment]
Hy @Noelle-San ! I think I am best for this issue. Can you assign this issue to me?

**Comment by Noelle-San** [comment]
Sure, go ahead. 
Add the issue Number as well as Screenshots in the Pull request

assigning to @zainulabideen1122

**Comment by Noelle-San** [comment]
Great work, thankyou @zainulabideen1122 for contributing
