### ISSUE TITLE
Covid Tracker

### ISSUE THREAD

**Issue by Noelle-San** [Noelle-San/Help-in-Covid#13]
A covid tracker page so that we can track the current covid situation of India.

Make a new "Covid_tracker.html" page. Add CSS, JS to it.  It must be properly working.
Add a Screenshot during PR

**Comment by Shivansh-yadav13** [comment]
@Noelle-San can you assign it to me, I would love to work on it?

**Comment by Noelle-San** [comment]
Sure go ahead, make sure you add Screenshots and mention the issue Number in the PR.
Else it might not be merged.

Assigning @Shivansh-yadav13

**Comment by Noelle-San** [comment]
Great work @Shivansh-yadav13 
Thankyou for participating.
