### ISSUE TITLE
Fix Navbar along with Good fonts. 

### ISSUE THREAD

**Issue by Noelle-San** [Noelle-San/Help-in-Covid#2]
Add proper fonts and fix the horizontal navbar

**Comment by ItsRoy69** [comment]
Can you assign me this?

**Comment by Noelle-San** [comment]
> Can you assign me this?

Assigned @ItsRoy69

**Comment by Noelle-San** [comment]
Mention the issue Number in your PR.

**Comment by Noelle-San** [comment]
Thankyou @ItsRoy69 for participating. To give chances to others we have decided to give just 1 issue per person. 
Keep contributing to other projects.
