### ISSUE TITLE
About Us

### ISSUE THREAD

**Issue by Noelle-San** [Noelle-San/Help-in-Covid#6]
Add an About Us page and write About this initiative with a good picture and proper UI

**Comment by IAmTamal** [comment]
Can i work on this ?

**Comment by Noelle-San** [comment]
> Can i work on this ?

Go for it , assigning @IAmTamal

**Comment by Noelle-San** [comment]
Mention the issue Number in your PR.

**Comment by Noelle-San** [comment]
Thankyou @IAmTamal for Participating.
